FROM node:18-alpine AS build
WORKDIR /app

ARG ENVIRONMENT

COPY frontend/ .

RUN npm i && \
    npm run build-${ENVIRONMENT}

FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80