# name: 'Build, Pack and Publish'
name: 'Test Cenas'
on:
  push:
    branches: [dev]
env:
  RELEASE_VERSION: 1.0.0-beta.$GITHUB_RUN_NUMBER
  DOTNET_VERSION: "7.0.102"
  NUPKG_SOURCE: "https://gitlab.example.com/api/v4/groups/caesareum/-/packages/nuget/index.json"
  NUPKG_ACCESS_TOKEN: "glpat-tDbyxsy33yAqXG3xZZF4"
jobs:
  main:
    name: main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build -c Release --no-restore
      - name: Test
        run: dotnet test --no-restore
      - name: Pack
        run: |
          for project in src/**/*.csproj; do\
            dotnet pack ${project} -c Release --no-restore --no-build -p:Version=${{ env.RELEASE_VERSION }} -o artifacts;\
          done
      - name: Publish Artifacts
        run: dotnet nuget push artifacts/*.nupkg -u morilon -k ${{ env.NUPKG_ACCESS_TOKEN }} -s ${{ env.NUPKG_SOURCE }} --skip-duplicate
